#!/use/bin/env ruby
require './lib/environment'

cli = Cli.new.parse
dst = Sequel.connect("postgres://#{cli.dest_user}:#{cli.dest_password}@#{cli.dest_host}:#{cli.dest_port}/postgres")
stat = dst.fetch("SELECT subid,subname,received_lsn,latest_end_lsn,latest_end_time FROM pg_stat_subscription")
stat.each do |row|
  puts "#{row[:subid]}\t#{row[:subname]}\t#{row[:latest_end_time]}\t#{row[:received_lsn]}\t#{row[:latest_end_lsn]}"
end
